local_repository(
    name = "rules_intellij",
    path = "../../",
)

load("@rules_intellij//intellij:repositories.bzl", "rules_intellij_repositories")
rules_intellij_repositories()

load("@rules_intellij//intellij:deps_repositories.bzl", "rules_intellij_deps_repositories")
rules_intellij_deps_repositories()

load("@rules_intellij//intellij:toolchains.bzl", "rules_intellij_all_toolchains")
rules_intellij_all_toolchains()